from src.networks.clip_plus import CLIPPlus
from src.networks.clip_plus_upernet import CLIPPlusUPerNet
from src.networks.cnn import CNN
from src.networks.mlp_unet import MLPUNet
from src.networks.mlp_unet_encoder import MLPUNetEncoder
from src.networks.mlp_unet_upernet import MLPUNetUPerNet
from src.networks.mlp_vit_upernet import MLPViTUPerNet
from src.networks.resnet50 import ResNet50
from src.networks.resnet_unet_decoder import ResNetUNetDecoder
from src.networks.transformer import Transformer
from src.networks.transformer_unet import TransformerUNet
from src.networks.unet_encoder import UNetEncoder
from src.networks.wair_d_non_ml import WAIRDNonML
from src.networks.wair_d_original import WAIRDOriginal
