from src.datamodules.wair_d_r_images import WAIRDRImagesDatamodule
from src.datamodules.wair_d_r_n_channels import WAIRDRNChannelsDatamodule
from src.datamodules.wair_d_r_n_channels_sequences import WAIRDRNChannelsSequencesDatamodule
from src.datamodules.wair_d_r_sequences import WAIRDRSequencesDatamodule
from src.datamodules.wair_d_r_var_channels import WAIRDRVarChannelsDatamodule
from src.datamodules.wair_d_r_var_channels_sequences import WAIRDRVarChannelsSequencesDatamodule
