# @package _global_
name: inference
seed: 0
print_config: True
ignore_warnings: True


checkpoint_path: ${oc.env:OUTPUT_DIR}/2023-12-20_12-01-24/checkpoints/epoch_0013.ckpt
gpu: 1
split: test
reconstruction: False
prediction_dir: ${oc.env:PREDICTIONS_PATH}/${split}

defaults:
  - datamodule: wair_d_images
  - algorithm: unet_erm
  - network: unet
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True