# @package _global_
name: prepare_data
seed: 0
print_config: True
ignore_warnings: True

raw_data_dir: ${oc.env:RAW_DATA_DIR}
prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

reconstruction: True
sequence: False
num_shortest_paths: 5
image_size: 224

n_processes: 8

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True