# @package _global_
name: train
seed: 0
print_config: True
ignore_warnings: True

defaults:
  - datamodule: wair_d_r_var_channels_sequences
  - optimizer: adam
  - scheduler: null
  - algorithm: r_transformer_unet
  - network: clip_plus_upernet
  - trainer: default
  - callbacks: default
  - loggers: [ aim ]
  - strategy: null
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True