_target_: src.datamodules.WAIRDImagesDatamodule

name: wair_d_images
data_path: ${oc.env:IMAGE_DATA_PATH}
scenario: scenario_1
scenario2_path: ${oc.env:SCENARIO2_PATH}
batch_size: 8
num_workers: 6
output_kernel_size: 3
kernel_size_decay: 1
use_channels: null
los_ratio: 1
input_kernel_size: null
no_supervision_image: False

